<a href="https://colab.research.google.com/github/PietroNozella/python-daily-projects/blob/main/Exerc%C3%ADcios_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Criando e manipulando arrays numpy.

In [4]:
import numpy as np

#criar um array 3x3 com valores aleatórios
array = np.random.random((3,3))
print ("Array Original")
print (array)

#encontrar o maior valor
max_value = np.max(array)
print ("Maior valor:", max_value)

#encontrar o menor valor
min_value = np.min(array)
print ("Menor valor:", min_value)

#somar os elementos do array
sum_elements = np.sum(array)
print ("Soma dos elementos:", sum_elements)

Array Original
[[0.6316984  0.58998646 0.2146814 ]
 [0.52947354 0.92001194 0.88442324]
 [0.09702721 0.92166315 0.00456483]]
Maior valor: 0.9216631538909537
Menor valor: 0.004564827622422052
Soma dos elementos: 4.793530172402547


2. Produto escalar entre vetores

In [6]:
import numpy as np

#criar dois vetores
vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

#calcular o produto escalar
produto_escalar = np.dot(vetor1, vetor2)

print("Vetor 1:", vetor1)
print("Vetor 2:", vetor2)

print("Produto Escalar:", produto_escalar)


Vetor 1: [1 2 3]
Vetor 2: [4 5 6]
Produto Escalar: 32


3. Operações matemáticas elementares.

In [8]:
import numpy as np

#criando dois arrays 2x2
array1 = np.array([[1, 2 ], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

#efetuando as operações
soma = array1 + array2
subtracao = array1 - array2
multiplicacao = array1 * array2

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

print("Soma:")
print(soma)

print("Subtração:")
print(subtracao)

print("Multiplicação:")
print(multiplicacao)


Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Soma:
[[ 6  8]
 [10 12]]
Subtração:
[[-4 -4]
 [-4 -4]]
Multiplicação:
[[ 5 12]
 [21 32]]


4. Fatiamento de arrays.

In [9]:
import numpy as np

#criando uma array 4x4
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

#obter o subarray 2x2
subarray = array [:2, :2]
print("Subarray:")
print(subarray)



Subarray:
[[1 2]
 [5 6]]


5. Transposição de arrays

In [11]:
import numpy as np

#criando uma array 3x2
array = np.array([[1,2], [3,4], [5,6]])

#calcular a transposta
transposta = np.transpose(array)
print("Transposta:\n", transposta)


Transposta:
 [[1 3 5]
 [2 4 6]]


6. Gerando matrizes de identidade.

In [12]:
import numpy as np

#criar uma matriz de indentidade 4x4
matriz_indentidade = np.eye(4)
print("Matriz de Identidade:")
print(matriz_indentidade)

Matriz de Identidade:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


7. Resolução de sistemas lineares.

In [14]:
import numpy as np

# coenficientes das equações
A = np.array([[2,1], [1,3]])
#resultados das equações
B = np.array([5,7])

#resolver s sistema
solucao = np.linalg.solve(A,B)
print("Solução do sistema:")
print(solucao)

Solução do sistema:
[1.6 1.8]


8. Média e Desvio Padrão

In [15]:
import numpy as np

#criar um array de 10 números aleatórios
array = np.random.rand(10)
print("Array Original:")
print(array)

#calcular média
media = np.mean(array)
print("Média", media)

#calcular o desvio padrão
desvio_padrao = np.std(array)
print("Desvio padrão", desvio_padrao)


Array Original:
[0.19848155 0.49022943 0.29465773 0.65396101 0.52104244 0.33200513
 0.05758666 0.60289203 0.83758085 0.49582474]
Média 0.44842615769072725
Desvio padrão 0.21891535589143313


9. Geração com linspace

In [1]:
import numpy as np

#gerar um array de 50 valores entre 0 e 10
array = np.linspace(0, 10, 50)
print("Array de 50 valores entre 0 e 10:", array)

Array de 50 valores entre 0 e 10: [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


10. Ordenação de array.

In [2]:
import numpy as np

#criar um array com 10 números aleatórios
array = np.random.rand(10)

#ordernar o array
array_ordenado = np.sort(array)
print("Array Original:", array)
print("Array Ordenado:", array_ordenado)



Array Original: [0.06862115 0.37410093 0.13563364 0.2916701  0.37870647 0.03850513
 0.90193027 0.7116304  0.18277685 0.91351499]
Array Ordenado: [0.03850513 0.06862115 0.13563364 0.18277685 0.2916701  0.37410093
 0.37870647 0.7116304  0.90193027 0.91351499]
